language: generic 
sudo: required
services:
  - docker
before_install:
  - docker builld -t bpintoleega/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true bpintoleega/docker-react npm run test